truncate table dbo.APBatches
truncate table dbo.APDeliveryType
truncate table dbo.APExpense
truncate table dbo.APPaymentTerms
truncate table dbo.APTaxOffice
truncate table dbo.APTaxReason
truncate table dbo.APTrans
truncate table dbo.APVendorAccounts
truncate table dbo.APVendorCategory
truncate table dbo.APVendorContacts
truncate table dbo.APVendors
truncate table dbo.Ar_AccontCat
truncate table dbo.ARAccountCat2
truncate table dbo.ARBankAccounts
truncate table dbo.ARCashFlowCategory
truncate table dbo.ARCheckBook
truncate table dbo.ARContacts
truncate table dbo.ARCredits
truncate table dbo.ARCustomerMaintainance
truncate table dbo.ARDiscountCategories
truncate table dbo.ARtrans
truncate table dbo.ARTransactionCodes
truncate table dbo.AvailableTable
truncate table dbo.BalanceSheet
truncate table dbo.GLTransactions
truncate table dbo.GLTransactionsTemp
truncate table dbo.BatchTemp
truncate table dbo.DepartmentCode
truncate table dbo.G_Report
truncate table dbo.G_Report_Col
truncate table dbo.G_Report_Col_Det
truncate table dbo.G_Report_Journal
truncate table dbo.G_Report_Row
truncate table dbo.G_Report_Row_Det
truncate table dbo.GenerateInvoice
truncate table dbo.GLAccounts
 dbo.GLAccountsChart delete all row exception first row
truncate table dbo.GLAllocation
truncate table dbo.GLAllocationDestinationAccounts
truncate table dbo.GLBudget
truncate table dbo.GLCurrency
truncate table dbo.GLCurrencyConversion
truncate table dbo.GLFiscalPeriod
truncate table dbo.GLFiscalPeriodSetup
truncate table dbo.GLGeneralSetup
truncate table dbo.GLJournalCodes
truncate table dbo.GLJournalVoucher
truncate table dbo.GLJVTransactionAccounts
truncate table dbo.GLProjectCodes
truncate table dbo.GLTemplateAccounts
truncate table dbo.GLTemplates
truncate table dbo.GLTotals
truncate table dbo.MyIncomes
truncate table dbo.MyJVs
truncate table dbo.RptVendorList
truncate table dbo.TrialBalance
truncate table dbo.TypeCategories
truncate table dbo.TypeCategory
truncate table dbo.Batch
